discourse/horizon

scss/search-banner.scss

This PR fixes the z-index overlap issue with the search results of the search-banner component and navigation-container.
Before (local testing):
After (local testing):
Dev:

UI: Fix overlap between search banner search results and nav container

---

about.json
locales/en.yml
scss/chat.scss
scss/header.scss
scss/main.scss
scss/search-banner.scss
scss/topic-cards.scss
scss/topic.scss
scss/variables.scss

More work to come but gets a usable dark mode in 
Before:
After:

UX: start removing hardcoded colors for dark mode support

---

about.json
javascripts/discourse/components/card/topic-author-avatar-column.gjs
javascripts/discourse/components/card/topic-author-column.gjs
javascripts/discourse/components/card/topic-category-column.gjs
javascripts/discourse/components/card/topic-likes-column.gjs
javascripts/discourse/components/card/topic-replies-column.gjs
javascripts/discourse/components/card/topic-status-column.gjs
javascripts/discourse/initializers/topic-list-columns.gjs
locales/en.yml
package.json
scss/topic-cards.scss
settings.yml

This PR merges the topic-list-item card component into the nextgen theme.
Also does the following cleanup:
* Use template-only ember components
* Use `fire` instead of deprecated `fa-fire` icon
* Lower version requirement for node to 18 to match core
* Add english locale strings for topic status column
* Remove dummy theme settings

DEV: Merge topic list card component

---

about.json
scss/box-view.scss
scss/buttons.scss
scss/chat.scss
scss/main.scss
scss/nav-pills.scss
scss/sidebar.scss
scss/topic.scss
scss/variables.scss

This PR:
- Renames theme to "Horizon"
- aligns button & hover status to match other elements
- adjusts problems with the boxed view
- adjusts box shadow to use variation of accent color using oklch
- adjusts with of chat / topic list / topic box & sets content to not go past max-width
- styles chat drawer to match some sidebar styles
- small additions to get padding correctly applied to containers
- adjustment to timeline width to keep content viewable
| before | after |
| -- | -- |
| ![CleanShot 2025-03-06 at 12 47 18@2x](https://github.com/user-attachments/assets/045fa947-25da-4e6c-a7ab-6216e4e04a73) | ![CleanShot 2025-03-06 at 12 42 39@2x](https://github.com/user-attachments/assets/48bf88ff-0266-402d-8aec-6ae14ccf3eca) |
|![CleanShot 2025-03-06 at 12 47 …

UX: More desktop tweaks

---

scss/main.scss
scss/search-banner.scss

This PR adjusts when padding is applied to the content in main container
https://github.com/user-attachments/assets/5cfcaf44-0b03-45b3-bd13-fa32430b3d1f
https://github.com/user-attachments/assets/4d1ac5c9-13d9-45f9-9aa3-4f8d01a05d3a

UX:Breakpoint padding

---

about.json

Followup dfa22d21b6a49bb4ebaf590b16578cbc35c2894e,
the search banner has been replaced in core
with the welcome banner, this is no longer needed,
c.f. https://github.com/discourse/discourse/pull/31516

DEV: Remove search banner dependency

---

scss/color-exploration.scss
scss/misc.scss

Re-adding the hover effect for buttons by making the button-box-shadow colour visible
VS

Button hover style reapply

---

scss/main.scss
scss/misc.scss

Still not ideal but a slight improvement to the fully-overlapping alert banner 
|--------|--------|
| ![CleanShot 2025-03-18 at 08 26 22](https://github.com/user-attachments/assets/433a9918-f1aa-4e55-a21f-ea3f46eaf1d5) | ![CleanShot 2025-03-18 at 08 24 33](https://github.com/user-attachments/assets/c8f97dc2-ad1c-46f5-a5cd-5cb3aa29aa35) |

Update styling of  overlapping alert new/updated topics

---

scss/topic.scss

We've had `-webkit-font-smoothing: antialiased` applied in the Horizon theme for awhile, but it was not applying to the content in the topic post stream for some reason. It will with this PR.
**Before**
**After**

UX: apply anti-aliased font to topics as well

---

scss/topic.scss

This PR fixes the admin wrench from not showing due to topic title z-index.

UX: Adjust topic timeline z-index

---

javascripts/discourse/api-initializers/horizon.gjs
javascripts/discourse/api-initializers/user-pallette.js
settings.yml

This commit adds the above for these core site
settings:
* search_experience
* enable_welcome_banner
Since for horizon we want better control of
the default experience of these settings OOTB.
See also https://github.com/discourse/discourse/pull/31917

UX: Add theme settings and value transformers

---

javascripts/discourse/components/card/topic-status-column.gjs
scss/topic-cards.scss

This PR:
- introduces logic to only show either the hot badge, or the pinned badge
- the hot badge takes precedence over pinned
- removes functionality to "unpin" a topic by clicking on the pinned badge
- adjusts some styles due to the changes

UX: Only show hot or pinned badges

---

about.json

This PR begins the migration toward using Discourse Core's color palettes instead of what is currently built into this theme.

DEV: begin migration of colors

---

about.json
javascripts/discourse/components/card/topic-status-column.gjs

This PR moves to use the new serializer in core to detect if topics should have the `hot` badge attached.
This PR should only be merged once this core change is merged -> https://github.com/discourse/discourse/pull/31935

DEV: Use new is_hot_topic serializer

---

scss/mobile-stuff.scss

In dark mode `--d-content-background` and `--secondary` don't match, causing this dropdown bg issue: 
Before:
After:

UX: change category nav background on mobile

---

scss/main.scss

This container was missing from the list
Before:
After:

UX: add tags-index container

---

javascripts/discourse/components/card/topic-activity-column.gjs
javascripts/discourse/initializers/topic-list-columns.gjs
locales/en.yml
scss/mobile-stuff.scss
scss/topic-cards.scss
spec/system/horizon_high_level_spec.rb

This PR addresses feedback of needing more context behind replies, updates, and other important information related to a topic when it is bumped to the top of a list. It also styles the status badge to slightly go outside of the container on larger widths.
|Desktop Before| Desktop After|
|--|--|
|![CleanShot 2025-03-26 at 08 23 13@2x](https://github.com/user-attachments/assets/25a715db-3235-4d8d-867b-5098746c0420)|![CleanShot 2025-03-26 at 08 21 30@2x](https://github.com/user-attachments/assets/d1d90f8d-2671-454c-933b-4a16aa42ddf2)|
|Mobile before|Mobile after|
|--|--|
|![CleanShot 2025-03-26 at 08 22 44@2x](https://github.com/user-attachments/assets/14de0889-3665-45b8-9152-c3e7a898eed4)|![CleanShot 2025-03-26 at 08 22 15@2x](https://github.com/user-attachments/assets/33be910d-bbfa-425d-81 …

UX: New topic card layout

---

javascripts/discourse/components/card/topic-activity-column.gjs
javascripts/discourse/components/card/topic-replies-column.gjs
javascripts/discourse/initializers/topic-list-columns.gjs
locales/en.yml
scss/topic-cards.scss
spec/system/horizon_high_level_spec.rb

This PR adjusts the topic card layout again a bit. It:
- Places title first & sub-info second. The activity data will now appear below the title.
- Adds more relevant text to the activity data `ago` and `on` when necessary
- Adjustments to breakpoints for when card changes from large view to smaller view
| -- | -- | 
| ![CleanShot 2025-03-27 at 14 49 42@2x](https://github.com/user-attachments/assets/fd84a1d9-a57d-4c38-b405-3a440315c4ff) | ![CleanShot 2025-03-27 at 14 44 12@2x](https://github.com/user-attachments/assets/4a71a62a-9c19-4236-a717-d7c588d6992b) |
| ![CleanShot 2025-03-27 at 14 49 26@2x](https://github.com/user-attachments/assets/bffdc605-f2dd-475f-88b7-c6ee975a52bb) | ![CleanShot 2025-03-27 at 14 44 …

UX: Topic list layout changes

---

scss/composer.scss
scss/misc.scss

A more lightweight and sleek styling for the theme. Only applies on desktop with preview hidden.
* removed area border
* moved focus indicator to grippie
* changed to one-colour background for entire element
|--------|--------|
| ![CleanShot 2025-03-27 at 16 35 20@2x](https://github.com/user-attachments/assets/8ad6c0db-5c49-43bd-a7fd-8371afe69548) | ![CleanShot 2025-03-27 at 16 35 01@2x](https://github.com/user-attachments/assets/c10c6687-8c68-4c07-9526-d2e975604be3) |

Composer styling on desktop

---

scss/topic-cards.scss

This needs a better follow-up, but the messages topic list
is currently busted. Removing the overridden topic-list-item
grid for messages helps.
**Before**
**After**

FIX: Messed up CSS grid on messages list

---

scss/misc.scss

Needs to be lowered to avoid overlap with composer

Lower z-index of powered-by-discourse badge

---

scss/mobile-stuff.scss

This adjusts the active state of the dropdown by employing negative margin to compensate for the padding 
before:
after:

UX: fix category nav padding on small screens

---

spec/system/core_feature_spec.rb

This uses the core feature shared example to make sure
Horizon is not mistakenly breaking anything in core

DEV: Add core feature spec

---

scss/topic.scss

Attempt to make the timeline less eye-drawing, while still enhancing the feel of "this is a draggable area" by emphasising the handle. Also added a slight decrease of width.
|--------|--------|
| ![CleanShot 2025-04-07 at 20 17 29@2x](https://github.com/user-attachments/assets/7997a797-1ffa-43b7-94fa-010974aeae51) | ![CleanShot 2025-04-07 at 20 17 02@2x](https://github.com/user-attachments/assets/7372e1e2-8530-4045-bcdf-0ef73aa6698e) |

UX:  iteration for the timeline scroll design

---

scss/main.scss
scss/topic.scss

This prevents us from having to guess at every possible container by selecting all the direct descendants

DEV: use wildcard selector for common container behavior

---

scss/main.scss

This PR fixes the experimental screen implementation. It was being broken by 
```
> * {
@include breakpoint(medium, $rule: min-width) {
box-sizing: border-box;
max-width: 1000px;
margin-inline: auto;
padding-inline: var(--spacing-inline-l);
}
```

UX: font set experimental screen styles

---

javascripts/discourse/components/card/topic-replies-column.gjs
javascripts/discourse/initializers/topic-list-columns.gjs
scss/topic-cards.scss
spec/system/horizon_high_level_spec.rb

This PR restyles PMs in the Horizon theme to more closely match typical inbox layouts. It also adds back in posters so you can see who is participating in the PM.
**Before**
**After**

UX: New PM design

---

about.json
desktop/desktop.scss
javascripts/discourse/api-initializers/full-width-logo-behavior.js

Removes the [full-width component](https://github.com/discourse/discourse-full-width-component) dependency by adding most of the code directly to the theme. There was one grid definition in the CSS I ended up removing because it was conflicting with an existing override in the theme. 
Anyone who has previously installed the theme should manually remove the full-width component from it.

DEV: port full-width component to be included directly

---

about.json
common/common.scss
javascripts/discourse/api-initializers/sidebar-new-topic-button-connector.js
javascripts/discourse/components/sidebar-new-topic-button.gjs
scss/sidebar-new-topic-button.scss
spec/system/anon_sidebar_topic_button_spec.rb
spec/system/sidebar_topic_button_spec.rb

This moves the [sidebar new topic button component](https://github.com/discourse/discourse-sidebar-new-topic-button) into the theme directly 
If you have installed this theme previously, you should manually remove the component.

DEV: port sidebar new topic component into theme

---

scss/topic.scss

UX: fix topic progress height

---

scss/main.scss

When the composer is open the `#main-outlet`'s bottom padding needs to match the composer height, so the content behind the composer can be scrolled into view.
Reported here: https://meta.discourse.org/t/help-us-test-horizon-our-newest-theme/360484/26?u=awesomerobot

UX: main-outlet needs dynamic bottom padding when composer open

---

scss/sidebar-new-topic-button.scss

Improves the disabled state of the new topic button in the sidebar by hiding the draft dropdown (which is inaccessible) and styling the tooltip like the end of the button
Before:
After:

UX: adjust disabled create button tooltip styles

---

scss/mobile-stuff.scss

This PR fixes a couple items in preview mode on the mobile composer.
**Before**
**After**

UX: Mobile composer fixes

---

common/common.scss
javascripts/discourse/api-initializers/composer-peek-toggle-connector.js
javascripts/discourse/components/composer-peek-mode-toggle.gjs
scss/composer-peek-mode.scss

This implements the [composer peek](https://github.com/discourse/composer-peek) component directly into the theme, and makes some minor adjustments to match theme styles:

DEV: implement composer peek mode directly in theme

---

scss/main.scss

Reported here: https://meta.discourse.org/t/help-us-test-horizon-our-newest-theme/360484/55?u=awesomerobot
We have a 1px gap here where we get kind of a half-container 
Before:
After:

UX: minor breakpoint gap fix

---

scss/composer-peek-mode.scss

This PR gives the peek-mode composer more room.

UX: Adjust spacing for more room

---

scss/desktop-full-width.scss

Helps avoid situations like this:
Some examples...
text-logos
image-logos

UX: better full-width support for wide logos

---

scss/desktop-full-width.scss

Minor adjustment to avoid clipping descenders 
before:
after:

UX: text logo line-height fix

---

scss/desktop-horizon-fixes.scss

These styles were added for bulk select positioning, but turns out they weren't needed anyway 
before:
after:

UX: fix experimental new new positioning

---

scss/desktop-full-width.scss

There are multiple header elements that get in the way, and we can't really manage the position of this button well without a better full-width solution... so I think it makes sense to hide it for now 
Before:
After:

UX: hide bootstrap mode from header

---

scss/main.scss

Only a tiny sliver of the background shows currently, which seems accidental 
Before:
After:

UX: exclude wizard from #main-outlet background styling

---

javascripts/discourse/api-initializers/hamburger-click-outside-transformer.js
javascripts/discourse/components/sidebar-new-topic-button.gjs
scss/sidebar.scss

We need to close the slide-in hamburger menu on mobile when new topic or a draft is opened from it, this should do it!

UX: handle opening composer from slide-in hamburger menu

---

javascripts/discourse/components/user-color-palette-selector.gjs

To repro this you had to unchecked all the "Color palette can be selected by users" from the colors tab.

FIX: do not error when no palettes are available

---

scss/chat.scss
scss/composer.scss

To avoid very strange positioning and sizing, I'm opting to keep the chat in front of the composer, when in peak-mode.
Still not ideal, but better than before.
⬇️ 
Due to the way peakmode positions itself, it's impossible to place the chat flush next to it. And due to the way resizing works (frop the top left, anchored right), it also can't be placed on any left-handed alignment.

Chat drawer and peakmode

---

scss/misc.scss

Improves compatibility with https://meta.discourse.org/t/top-contributors-sidebar/215110
Before:
After:

UX: add compatibility with the top contributors sidebar

---

scss/chat.scss

UX: fix low z-index for popup after changes to composer-drawer interaction

---

scss/topic-cards.scss

this regressed slightly with core changes 
before:
after:

UX: adjust event date alignment with topic titles

---

scss/topic-cards.scss

The theme implements this in a centralized way, so we need to remove the core implementation. 
before:
after:

UX: fix new topic badge in topic list

---

javascripts/discourse/components/card/topic-activity-column.gjs
javascripts/discourse/components/card/topic-creator-column.gjs
javascripts/discourse/initializers/topic-list-columns.gjs
scss/desktop-horizon-fixes.scss
scss/main.scss
scss/topic-cards.scss
spec/system/horizon_high_level_spec.rb

This is the second iteration on the topic card design, in which we bring back the OP and change the layout.
**Changes**:
* Show OP avatar
* Remove activity avatar and replace by reply icon
* Remove activity icon background
* Move category tag to top left
* Replace long activity copy ("…replied at…") with dot separator
* Change date formatting to `tiny`
* Adjust bulk select styling to new layout + align checkbox to top on mobile VS keep centred on desktop
* Why: On desktop, the avatar is taking 2 lines (usually) and aligning the checkbox vertically looks nice. Exception for excerpts, but since that's only available for pinned topics atm that's a low occurrence.  On mobile, the topic card is 3 lines, with a smaller avatar, which makes the checkbox "float" around a bit when centred. Hence …

UX: Topic cards v2

---

scss/topic.scss

Since the title is no longer sticky, I think we can drop all of this @jordanvidrine? The z-index puts the timeline behind the footer controls in the PWA
Before:
After:

UX: fix mobile timeline in PWA

---

scss/box-view.scss

This line removal solves two purposes:
- it was not needed
- its removal fixes a rendering bug in safari on ipad

UX: Remove unused line & fix ipad safari browser

---

scss/chat.scss
scss/mobile-stuff.scss
scss/nav-pills.scss

* Changing the category & tag dropdown back into their original form. The breadcrumb idea isn't working well.
| BC | AC |
|--------|--------|
| ![CleanShot 2025-06-09 at 18 59 37@2x](https://github.com/user-attachments/assets/cbeb3aaf-ad0e-4085-8548-58ea0a521c95) | ![CleanShot 2025-06-09 at 18 57 33@2x](https://github.com/user-attachments/assets/15db752b-4983-4b7f-b6f8-9a8ded9e6f9f) | 
* Alignment fix in chat navbar drawer
| BC | AC |
|--------|--------|
| ![CleanShot 2025-06-09 at 18 59 18@2x](https://github.com/user-attachments/assets/38c7dcee-dc77-4a44-ae8d-5ecb7910536b) | ![CleanShot 2025-06-09 at 18 58 36@2x](https://github.com/user-attachments/assets/be699f88-4e5e-4d8c-ab4d-f6d1eca93037) |

UX: Mini fixes and tweaks

---

scss/topic-cards.scss

The left-border select state when using keyboard navigation is already overruled in Horizon, but when bulk-select is enabled, this still showed up:
Fixed:

UX: remove default select state for keyboard nav on topic cards

---

scss/main.scss

Until we move forward with the search-banner on mobile, the welcome-message feels out of place. Hiding it for now.

UX: hide welcome banner
