discourse/horizon

scss/main.scss, scss/misc.scss, scss/nav-pills.scss, scss/topic.scss, scss/variables.scss
=> UX: More small fixes

javascripts/discourse/api-initializers/next-gen.gjs, javascripts/discourse/components/experimental-screen.gjs, scss/box-view.scss, scss/chat.scss, scss/header.scss, scss/main.scss, scss/sidebar.scss, scss/topic-cards.scss, scss/topic.scss, scss/variables.scss
In this PR:
- I refactor & update the "box-view" component and styles to work better
- Adjust some z-index issues with topic title
- make the background for chat the same as other pages
- fix multiple content areas for correct padding application
- remove letter spacing from sidebar as the increased font size made this look off
- correctly scope the increased font-size in topics to apply to all elements
=> UX: Misc desktop edits

common/common.scss, scss/box-view.scss, scss/buttons.scss, scss/header.scss, scss/hiddenstuff.scss, scss/main.scss, scss/mobile-stuff.scss, scss/sidebar.scss, scss/topic-cards.scss, scss/topic.scss
First basic styling for mobile mainpages.
=> Mobile: Topic list and topic

scss/main.scss, scss/misc.scss, scss/topic-cards.scss, scss/topic.scss
This PR addresses and fixes:
- mobile chat index page
- mobile timeline
- bulk select topic list item styling
- link color
=> UX: More tweaks & fixes

common/color_definitions.scss, scss/box-view.scss, scss/buttons.scss, scss/chat.scss, scss/nav-pills.scss, scss/search-banner.scss, scss/topic-cards.scss, scss/variables.scss
This PR changes the way some colors are derived for dark/light modes.
|before|after|
|--|--|
|![CleanShot 2025-03-06 at 20 22 08@2x](https://github.com/user-attachments/assets/0104dc41-1878-462d-844c-a6a96bbb7242)|![CleanShot 2025-03-06 at 20 06 17@2x](https://github.com/user-attachments/assets/bd203e19-1a84-41ce-bb69-4737f8cff220)|
=> UX: Dark mode changes to move toward a base of accent-color

scss/topic.scss
This fixes the z index on wide screens.
=> UX: Topic title z-index wide screen

javascripts/discourse/components/custom-user-pallette.gjs, scss/buttons.scss, scss/color-choice.scss, scss/color-exploration.scss, scss/header.scss, scss/sidebar.scss, scss/topic-cards.scss
This PR addresses lots of small tweaks.
=> UX: Color fixes

scss/misc.scss
Hiding this toggle for now as it has not been designed for just yet.
=> UX: hide topic list trigger

javascripts/discourse/components/card/topic-replies-column.gjs, scss/buttons.scss, scss/chat.scss, scss/hiddenstuff.scss
This PR:
- does not show reply count if only 1 "op" post exists
- fixes chat message buttons
- chat window z index issues
- shows messages in sidebar
=> UX: More fixes

scss/buttons.scss, scss/color-exploration.scss, scss/header.scss
This PR cleans up the buttons scss stylesheet. I have tested a good bit of the pages and the buttons remain 99% the same with much less code. 
Can revert if we notice anything drastic.
=> DEV: Button stylesheet cleanup

scss/chat.scss, scss/main.scss
This PR cleans up the `main.scss` file along with fixing a couple of grid issues causing responsive issues on certain pages 
like the user page.
**Before**
**After**
=> DEV: main container sizing & border radius cleanup

scss/main.scss, scss/search-banner.scss
This PR preps the Horizon theme for the merger of the search banner into core. This PR should only be merged once [this PR in core has been merged](https://github.com/discourse/discourse/pull/31516).
=> UX: Welcome banner merge prep

scss/main.scss, scss/misc.scss
This PR applies the correct styling to all user pages, instead of just your own.
=> UX: fix user page

scss/search-banner.scss
Cleanup due to changes in core
=> DEV: cleanup scss

scss/main.scss
=> Mobile: New alert info width fix

scss/nav-pills.scss
Set list control z-index to base
=> UX: Z-index welcome banner

scss/search-banner.scss
Another mini correction follow up for #68
=> Welcome banner: slight zindex increase

scss/topic.scss
=> UX: set border radius on PMs

javascripts/discourse/initializers/topic-list-columns.gjs, scss/topic-cards.scss
This PR:
- adjusts topic list card items to work for bookmarks & assignments
- adjusts some mobile styling
| -- | -- |
| ![CleanShot 2025-03-25 at 12 05 46@2x](https://github.com/user-attachments/assets/d2300025-fccf-4f69-af51-fa3ec746c79b) | ![CleanShot 2025-03-25 at 12 05 31@2x](https://github.com/user-attachments/assets/3ce80613-aba1-40be-9704-cc6282d7a285) | 
|![CleanShot 2025-03-25 at 12 06 10@2x](https://github.com/user-attachments/assets/ccc6661e-9bd2-4565-b251-18e22c48c3d0)| ![CleanShot 2025-03-25 at 12 06 33@2x](https://github.com/user-attachments/assets/8f0b8d71-cd07-4ac4-aec9-2bf692589a4e)|
=> UX: Topic list card fixes for assignments & bookmarks

scss/topic-cards.scss
This PR addresses some font sizing & spacing issues in the topic card layout.
|Before|After|
|--|--|
| ![CleanShot 2025-03-26 at 13 14 12@2x](https://github.com/user-attachments/assets/b79b939b-433e-4ed2-ac3c-5c016f76cc3c)| ![CleanShot 2025-03-26 at 13 12 37@2x](https://github.com/user-attachments/assets/d4812c5d-28ae-4ae4-91df-8f17f875187b)|
|![CleanShot 2025-03-26 at 13 13 50@2x](https://github.com/user-attachments/assets/49bd9dcd-0bbc-4538-bc89-15649c5bf338)|![CleanShot 2025-03-26 at 13 13 15@2x](https://github.com/user-attachments/assets/89ded1fd-4af6-4913-80de-c38627c7fcdd)|
=> UX: Change title fonts, etc

desktop/desktop.scss, scss/topic-cards.scss
This PR fixes bulk select on the new topic cards.
=> FIX: Bulk select fix

spec/system/horizon_high_level_spec.rb
This class is no longer present in core.
=> DEV: Fix spec

scss/composer.scss
=> UX: fix minimised draft bg colour for composer

scss/topic-cards.scss
This PR:
fixes topic cards from being too wide at the tablet width
fixes assigned, bookmarks, and messages
removes some classes from card
=> UX: More card fixes

javascripts/discourse/components/user-color-palette-selector.gjs
Followup 6a4b979514c19bca33ef4759adb52d990dfdc56f
In this commit I changed how we load the selected palette
stylesheet so the system specs would know when the CSS is actually
loaded, however this introduced an issue where the user would see
a FOUC when switching palettes. I also introduced a bug where
if you chose to force dark mode then switched the palette, you would
see light mode instead.
This commit fixes both issues, by swapping the CSS link with a preloaded
one then waiting for the preload before switching the href of the
existing link, and removes `mode` shenanigans causing the light mode
issue.
=> FIX: Issues with FOUC and dark mode when switching palettes

about.json
This PR defines the header colors.
=> UX: Define header colors

scss/topic-cards.scss
This PR fixes topic cards with excerpts.
=> UX: Topic excerpt fix

about.json, common/color_definitions.scss, scss/buttons.scss, scss/color-exploration.scss
This PR makes some of the colors of horizon palettes a bit more accessible.
**Royal**
=> UX: More accessible colors

scss/topic.scss
=> UX: post notice styling

scss/topic-cards.scss
This PR fixes some of the mobile issues with the new PM layout in Horizon theme.
**After**
**Before**
=> UX: Visual fixes

desktop/desktop.scss, scss/box-view.scss, scss/header.scss, scss/main.scss
This PR fixes some spacing & background color issues in the chat pages.
**Before**
**After**
=> UX: Fix chat backgrounds

scss/topic-cards.scss
This PR adjusts spacing on avatars.
=> UX: Adjust avatar spacing

common/common.scss, javascripts/discourse/components/experimental-screen.gjs, scss/login.scss, scss/main.scss
This PR slightly adjusts some of the login pages to keep it in line with the rest of the horizon theme.
=> UX: Login layout fixes

scss/nav-pills.scss, scss/topic-cards.scss
This PR: 
- Fixes username wrapping
- Fixes transparency issues on scrolling `/categories`
=> UX: Quick fixes

README.md, about.json
Just a little bit of metadata cleanup
=> UX: update about.json, readme

scss/box-view.scss, scss/desktop-horizon-fixes.scss, scss/main.scss, scss/topic-cards.scss, scss/topic.scss
This fixes the SCSS mixed declaration errors (most noticeable while running rspec)
=> FIX: remove SCSS mixed declarations

common/common.scss, scss/welcome-banner.scss
Horizon is targeting the welcome banner not the search component anymore, update CSS class names and rename the file to make this clearer
=> DEV: Rename search -> welcome banner

scss/welcome-banner.scss
This PR fixes the style target to adjust for core changes.
=> UX: adjust styles to meet core changes

scss/topic-cards.scss
Slightly bigger spacing to match the bigger avatars (bigger elements => more spacing to balance it out)
=> UX: increase spacing of topic cards

javascripts/discourse/components/card/topic-creator-column.gjs
=> DEV: Topic creator fix

javascripts/discourse/components/card/topic-activity-column.gjs, javascripts/discourse/components/card/topic-status-column.gjs, scss/topic-cards.scss, spec/system/horizon_high_level_spec.rb, spec/system/page_objects/components/user_color_palette_selector.rb, spec/system/user_color_palette_selector_spec.rb
=> UX: fix topic cards layout for messages with has-replies class

javascripts/discourse/components/card/topic-replies-column.gjs
=> UX: show replies in shortened form

scss/main.scss
Followup ffa86a0c467165b2abe77bfc6208e031f9c9b3bd
=> UX: Only hide welcome banner on mobile devices
